# Usa una imagen base de PHP
FROM php:7.4-apache
FROM mysql:5.7

# Copia los archivos de la aplicación al contenedor
COPY . /var/www/html/

# Expone el puerto 80 para el servidor web Apache
EXPOSE 80
